client:
  infer_url: "http://127.0.0.1:18080"
  endpoint: "/infer"
  timeout_s: 60.0
  run_time_s: 0.0
  log_interval: 10
  task: "Put the eraser into the small box"

robot:
  robot_id: "hfy_follower"
  robot_port: "/dev/serial/by-id/usb-1a86_USB_Single_Serial_5A7C123192-if00"
  calib_dir: "/home/cqy/.cache/huggingface/lerobot/calibration/robots/so_follower"
  max_relative_target: 10.0
  top_cam: "/dev/video4"
  wrist_cam: "/dev/video6"
  top_cam_fourcc: "YUYV"
  wrist_cam_fourcc: "MJPG"
  img_width: 640
  img_height: 480
  fps: 30
  motor_io_retries: 10

executor:
  execute_actions: false
  action_chunk_steps: 30
  control_fps: 30.0
  policy_fps: 30.0
  interpolate_actions: false
  boundary_blend_steps: 0
  max_action_delta_per_step: 0.0
  action_ema_alpha: 1.0
  dry_run: false
  async_prefetch: true
  prefetch_after_steps: 25
